### ISSUE TITLE
Cannot run tests when source or test code is written in typescript.

### ISSUE THREAD

**Issue by vangorra** [meteor-typescript/meteor-typescript-compiler#44]
At first I thought I was doing something incorrect in my source files. So I removed all the code and added a simple var export. The same error is thrown.

Any ideas?

``` javascript
// package.js
Package.describe({
  name: 'vangorra:ledge-util',
  version: '0.0.2',
  // Brief, one-line summary of the package.
  summary: '',
  // URL to the Git repository containing the source code for this package.
  git: '',
  // By default, Meteor will default to using README.md for documentation.
  // To avoid submitting documentation, set this field to null.
  documentation: 'README.md'
});

Package.onUse(function(api) {
    api.versionsFrom('1.2.1');
    api.use('meteortypescript:compiler');
    api.use('systemjs:systemjs');
    api.addFiles('ledge-util.ts');
});

Package.onTest(function(api) {
    api.use([
        'tinytest',
        'test-helpers',
        'meteortypescript:compiler',
        'systemjs:systemjs',
        'vangorra:ledge-util'
    ]);
    api.addFiles('ledge-util-tests.ts');
});
```

``` sh
meteor test-packages vangorra:ledge-util
```

```
   While building package vangorra:ledge-util:
   error: No plugin known to handle file 'ledge-util.ts'. If you want this file to be a static asset, use addAssets instead of addFiles; eg, api.addAssets('ledge-util.ts', 'client').
 
   While loading plugin `compileTypescript` from package `meteortypescript:compiler`:
   native: Cannot redefine property: to
   at defineProperty (native)
   at Function.defineProperty
   (/Users/vangorra/.meteor/packages/meteor-tool/.1.1.10.1j7yym4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/core-js/modules/es6.symbol.js:75:12)
   at defineProperty
   (/Users/vangorra/.meteor/packages/meteortypescript_compiler/.0.0.12.1bwxjqy++os+web.browser+web.cordova/plugin.compileTypescript.os/npm/compileTypescript/node_modules/node-persist/node_modules/sugar/release/sugar-full.development.js:148:14)
   at Object.<anonymous>
   (/Users/vangorra/.meteor/packages/meteortypescript_compiler/.0.0.12.1bwxjqy++os+web.browser+web.cordova/plugin.compileTypescript.os/npm/compileTypescript/node_modules/node-persist/node_modules/sugar/release/sugar-full.development.js:107:9)
   at iterateOverObject
   (/Users/vangorra/.meteor/packages/meteortypescript_compiler/.0.0.12.1bwxjqy++os+web.browser+web.cordova/plugin.compileTypescript.os/npm/compileTypescript/node_modules/node-persist/node_modules/sugar/release/sugar-full.development.js:210:13)
   at extend
   (/Users/vangorra/.meteor/packages/meteortypescript_compiler/.0.0.12.1bwxjqy++os+web.browser+web.cordova/plugin.compileTypescript.os/npm/compileTypescript/node_modules/node-persist/node_modules/sugar/release/sugar-full.development.js:100:5)
   at
   /Users/vangorra/.meteor/packages/meteortypescript_compiler/.0.0.12.1bwxjqy++os+web.browser+web.cordova/plugin.compileTypescript.os/npm/compileTypescript/node_modules/node-persist/node_modules/sugar/release/sugar-full.development.js:5933:3
   at Object.<anonymous>
   (/Users/vangorra/.meteor/packages/meteortypescript_compiler/.0.0.12.1bwxjqy++os+web.browser+web.cordova/plugin.compileTypescript.os/npm/compileTypescript/node_modules/node-persist/node_modules/sugar/release/sugar-full.development.js:8637:3)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/Users/vangorra/.meteor/packages/meteortypescript_compiler/.0.0.12.1bwxjqy++os+web.browser+web.cordova/plugin.compileTypescript.os/npm/compileTypescript/node_modules/node-persist/node-persist.js:10:14)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object._.extend.Npm.require (/tools/isobuild/bundler.js:1324:22)
   at Package (packages/compileTypescript/plugin/compile-typescript.js:4:1)
   at <runJavaScript-34>:183:4
   at <runJavaScript-34>:190:3
   
```

**Comment by vangorra** [comment]
Looks like simply adding the typscript compiler to the package dependencies don't mean the ts files are transpiled.

I posted a potential solution on this issue:
https://github.com/meteor-typescript/meteor-typescript-compiler/issues/22#issuecomment-163849816
