### ISSUE TITLE
Exclude property of tsconfig.json not working

### ISSUE THREAD

**Issue by IljaKroonen** [meteor-typescript/meteor-typescript-compiler#55]
I have a node (typescript) project that is a subdirectory of my meteor project. It contains .ts files I do NOT want to be compiled by the meteor typescript compiler.

I tried to exclude my folder like this in my tsconfig.json:
```
"exclude": [
      "csv-processor"
]
```

But I get a very long stacktrace everytime I run the compiler:

```
C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\meteor-typescript\compile-service.js:21:10: "undefined" == true
   at CompileService.CP.compile
   (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\meteor-typescript\compile-service.js:21:10)
   at compile (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\meteor-typescript\index.js:179:33)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\meteor-typescript\index.js:195:14
   at Cache.CCp.get (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\meteor-typescript\cache.js:168:19)
   at TSBuild.BP.emit (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\meteor-typescript\index.js:192:29)
   at packages/barbatus:typescript-compiler/typescript-compiler.js:82:28
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:324:29
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:96:7
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\ensemblo\AppData\Local\.meteor\packages\barbatus_typescript\0.3.3\plugin.typescript.os\npm\node_modules\meteor\barbatus_typescript-compiler\node_modules\async\lib\async.js:221:35)
   at TypeScriptCompiler.processFilesForTarget (packages/barbatus:typescript-compiler/typescript-compiler.js:64:11)
```

For now, I am using a hack (I put a "." in front of my subfolder name).

**Comment by barbatus** [comment]
Exact patterns will be added in the next version. For now use csv-processor/**

**Comment by barbatus** [comment]
Update barbatus:typescript-compiler to 0.6.11

**Comment by itayb8** [comment]
Hey I got this error: 
   at packages/barbatus:typescript-compiler/typescript-compiler.js:121:7
   at
   /Users/itayb/.meteor/packages/barbatus_typescript/.0.4.1.1lhdbmo++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
   at replenish
   (/Users/itayb/.meteor/packages/barbatus_typescript/.0.4.1.1lhdbmo++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
   at
   /Users/itayb/.meteor/packages/barbatus_typescript/.0.4.1.1lhdbmo++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
   at
   /Users/itayb/.meteor/packages/barbatus_typescript/.0.4.1.1lhdbmo++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:121:7
   at
   /Users/itayb/.meteor/packages/barbatus_typescript/.0.4.1.1lhdbmo++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
   at replenish
   (/Users/itayb/.meteor/packages/barbatus_typescript/.0.4.1.1lhdbmo++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
   at
   /Users/itayb/.meteor/packages/barbatus_typescript/.0.4.1.1lhdbmo++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (/Users/itayb/.meteor/packages/barbatus_typescript/.0.4.1.1lhdbmo++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:221:35)
   at TypeScriptCompiler.processFilesForTarget
   (packages/barbatus:typescript-compiler/typescript-compiler.js:89:11)

can someone help me
